---
- name: Import packages
  include_vars: "packages.yml"

- name: Install system packages
  apt: name={{ item }} state=present
  loop: "{{ system_packages }}"
  tags:
    - initial_setup

- name: Download Python 3.6.7
  unarchive:
    src: "https://www.python.org/ftp/python/3.6.7/Python-3.6.7.tgz"
    dest: /tmp/
    creates: /tmp/Python-3.6.7
    remote_src: yes
  tags:
    - initial_setup
    - python_tools

- name: Install Python 3.6.7
  shell: "./configure --enable-optimizations && make altinstall"
  args:
    chdir: /tmp/Python-3.6.7
  tags:
    - initial_setup
    - python_tools

- name: Install Python packages
  pip: name={{ item }} state=present
  loop: "{{ python_packages }}"
  tags:
    - initial_setup
    - python_tools
  
- name: Download boost c++ libraries
  unarchive:
    src: "https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.bz2"
    dest: /tmp/
    creates: /tmp/boost_1_68_0
    remote_src: yes
  tags:
    - cplusplus_tools

- name: Install boost c++ libraries
  command: "./bootstrap.sh; ./b2 install"
  args:
    chdir: /tmp/boost_1_68_0
  tags:
    - cplusplus_tools
