- name: import packages
  include_vars: "packages.yml"

- name: install system packages
  apt: name={{ item }} state=present
  loop: "{{ system_packages }}"

# Set Up Python and Install Required Python Packages
- name: set up python
  apt: name=python3-pip state=present

- name: install pip setuptools
  pip: name=setuptools state=present

- name: install python packages
  pip: name={{ item }} state=present
  loop: "{{ python_packages }}"
  
