---
- name: import packages
  include_vars: "packages.yml"

- name: install system packages
  apt: name={{ item }} state=present
  loop: "{{ system_packages }}"

- name: download boost c++ libraries
  unarchive:
    src: https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.bz2
    dest: /tmp/
    creates: /tmp/boost_1_68_0
    remote_src: yes

- name: install boost c++ libraries
  shell: ./bootstrap.sh && ./b2 install
  args:
    chdir: /tmp/boost_1_68_0

# Set Up Python and Install Required Python Packages
- name: set up python
  apt: name=python3.6-pip state=present

- name: install pip setuptools
  pip: name=setuptools state=present

- name: install python packages
  pip: name={{ item }} state=present
  loop: "{{ python_packages }}"
  
