python_packages:
  - ansible
  - bs4
  - python-logstash
  - numpy
  - pandas
  - psycopg2
  - scipy
  - xgboost

system_packages:
  - cmake
  - g++
  - gedit
  - postgresql
  - postgresql-contrib
  - vim
